# Generated by Django 5.1.2 on 2024-11-13 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='currency',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
