# Generated by Django 5.1.2 on 2025-04-26 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_expense_amount_in_target_currency_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="place",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="expense",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Жилищные расходы", "Жилищные расходы"),
                    ("Коммунальные услуги", "Коммунальные услуги"),
                    ("Транспорт", "Транспорт"),
                    ("Продукты", "Продукты"),
                    ("Питание вне дома", "Питание вне дома"),
                    ("Здравоохранение", "Здравоохранение"),
                    ("Погашение долгов", "Погашение долгов"),
                    ("Страхование", "Страхование"),
                    ("Одежда", "Одежда"),
                    ("Развлечения", "Развлечения"),
                    ("Образование", "Образование"),
                    ("Товары для детей", "Товары для детей"),
                    ("Уход за животными", "Уход за животными"),
                    ("Подписки", "Подписки"),
                    ("Прочее", "Прочее"),
                ],
                max_length=100,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="expense",
            name="receipt_image",
            field=models.ImageField(upload_to="cheques/"),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="target_currency",
            field=models.CharField(blank=True, default="RUB", max_length=3, null=True),
        ),
    ]
